/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  content: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author: AuthorReference;
  publishedAt: string;
  readingTime?: string;
  category: string;
  tags: Array<string>;
  featured?: boolean;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  avatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | AuthorReference
  | Post
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: ../next-js/src/sanity/queries.ts
// Variable: ALL_POSTS_QUERY
// Query: *[  _type == "post"  && defined(slug.current)]|order(publishedAt desc){  _id,  title,  excerpt,  content,  "slug": slug.current,  coverImage,  "author": {    "name": author->name,    "avatar": author->avatar  },  publishedAt,  readingTime,  category,  tags,  featured}
export type ALL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  excerpt: string;
  content: string;
  slug: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author: {
    name: string;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  publishedAt: string;
  readingTime: string | null;
  category: string;
  tags: Array<string>;
  featured: boolean | null;
}>;

// Source: ../next-js/src/sanity/queries.ts
// Variable: FEATURED_POSTS_QUERY
// Query: *[  _type == "post"  && defined(slug.current)  && featured == true]|order(publishedAt desc){  _id,  title,  excerpt,  content,  "slug": slug.current,  coverImage,  "author": {    "name": author->name,    "avatar": author->avatar  },  publishedAt,  readingTime,  category,  tags,  featured}
export type FEATURED_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  excerpt: string;
  content: string;
  slug: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author: {
    name: string;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  publishedAt: string;
  readingTime: string | null;
  category: string;
  tags: Array<string>;
  featured: true;
}>;

// Source: ../next-js/src/sanity/queries.ts
// Variable: SINGLE_POST_QUERY
// Query: *[  _type == "post"  && slug.current == $slug][0]{  _id,  title,  excerpt,  content,  "slug": slug.current,  coverImage,  "author": {    "name": author->name,    "avatar": author->avatar  },  publishedAt,  readingTime,  category,  tags,  featured}
export type SINGLE_POST_QUERY_RESULT = {
  _id: string;
  title: string;
  excerpt: string;
  content: string;
  slug: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author: {
    name: string;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  publishedAt: string;
  readingTime: string | null;
  category: string;
  tags: Array<string>;
  featured: boolean | null;
} | null;

// Source: ../next-js/src/sanity/queries.ts
// Variable: RELATED_POSTS_QUERY
// Query: *[  _type == "post"  && slug.current != $slug  && (category == $category || count((tags)[@ in $tags]) > 0)]|order(publishedAt desc)[0...3]{  _id,  title,  excerpt,  content,  "slug": slug.current,  coverImage,  "author": {    "name": author->name,    "avatar": author->avatar  },  publishedAt,  readingTime,  category,  tags,  featured}
export type RELATED_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  excerpt: string;
  content: string;
  slug: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author: {
    name: string;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  publishedAt: string;
  readingTime: string | null;
  category: string;
  tags: Array<string>;
  featured: boolean | null;
}>;

// Source: ../next-js/src/sanity/queries.ts
// Variable: RECENT_POSTS_QUERY
// Query: *[  _type == "post"  && slug.current != $slug  && !(_id in $existingIds)]|order(publishedAt desc)[0...3]{  _id,  title,  excerpt,  content,  "slug": slug.current,  coverImage,  "author": {    "name": author->name,    "avatar": author->avatar  },  publishedAt,  readingTime,  category,  tags,  featured}
export type RECENT_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  excerpt: string;
  content: string;
  slug: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author: {
    name: string;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  publishedAt: string;
  readingTime: string | null;
  category: string;
  tags: Array<string>;
  featured: boolean | null;
}>;

// Source: ../next-js/src/sanity/queries.ts
// Variable: POSTS_BY_CATEGORY_QUERY
// Query: *[  _type == "post"  && defined(slug.current)  && category == $category]|order(publishedAt desc){  _id,  title,  excerpt,  content,  "slug": slug.current,  coverImage,  "author": {    "name": author->name,    "avatar": author->avatar  },  publishedAt,  readingTime,  category,  tags,  featured}
export type POSTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  excerpt: string;
  content: string;
  slug: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author: {
    name: string;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  publishedAt: string;
  readingTime: string | null;
  category: string;
  tags: Array<string>;
  featured: boolean | null;
}>;

// Source: ../next-js/src/sanity/queries.ts
// Variable: POSTS_BY_TAG_QUERY
// Query: *[  _type == "post"  && defined(slug.current)  && $tagName in tags]|order(publishedAt desc){  _id,  title,  excerpt,  content,  "slug": slug.current,  coverImage,  "author": {    "name": author->name,    "avatar": author->avatar  },  publishedAt,  readingTime,  category,  tags,  featured}
export type POSTS_BY_TAG_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  excerpt: string;
  content: string;
  slug: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author: {
    name: string;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  publishedAt: string;
  readingTime: string | null;
  category: string;
  tags: Array<string>;
  featured: boolean | null;
}>;

// Source: ../next-js/src/sanity/queries.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: array::unique(*[  _type == "post"  && defined(category)].category)
export type ALL_CATEGORIES_QUERY_RESULT = Array<string>;

// Source: ../next-js/src/sanity/queries.ts
// Variable: ALL_TAGS_QUERY
// Query: array::unique(*[  _type == "post"  && defined(tags)].tags[])
export type ALL_TAGS_QUERY_RESULT = Array<string>;

// Source: ../next-js/src/sanity/queries.ts
// Variable: SEARCH_POSTS_QUERY
// Query: *[  _type == "post"  && defined(slug.current)  && (    title match $searchPattern ||    excerpt match $searchPattern ||    content match $searchPattern ||    category match $searchPattern  )]|order(publishedAt desc){  _id,  title,  excerpt,  content,  "slug": slug.current,  coverImage,  "author": {    "name": author->name,    "avatar": author->avatar  },  publishedAt,  readingTime,  category,  tags,  featured}
export type SEARCH_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  excerpt: string;
  content: string;
  slug: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author: {
    name: string;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  publishedAt: string;
  readingTime: string | null;
  category: string;
  tags: Array<string>;
  featured: boolean | null;
}>;

// Source: ../next-js/src/sanity/queries.ts
// Variable: ALL_POST_SLUGS_QUERY
// Query: *[  _type == "post"  && defined(slug.current)]{"slug": slug.current}
export type ALL_POST_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "post"\n  && defined(slug.current)\n]|order(publishedAt desc){\n  _id,\n  title,\n  excerpt,\n  content,\n  "slug": slug.current,\n  coverImage,\n  "author": {\n    "name": author->name,\n    "avatar": author->avatar\n  },\n  publishedAt,\n  readingTime,\n  category,\n  tags,\n  featured\n}': ALL_POSTS_QUERY_RESULT;
    '*[\n  _type == "post"\n  && defined(slug.current)\n  && featured == true\n]|order(publishedAt desc){\n  _id,\n  title,\n  excerpt,\n  content,\n  "slug": slug.current,\n  coverImage,\n  "author": {\n    "name": author->name,\n    "avatar": author->avatar\n  },\n  publishedAt,\n  readingTime,\n  category,\n  tags,\n  featured\n}': FEATURED_POSTS_QUERY_RESULT;
    '*[\n  _type == "post"\n  && slug.current == $slug\n][0]{\n  _id,\n  title,\n  excerpt,\n  content,\n  "slug": slug.current,\n  coverImage,\n  "author": {\n    "name": author->name,\n    "avatar": author->avatar\n  },\n  publishedAt,\n  readingTime,\n  category,\n  tags,\n  featured\n}': SINGLE_POST_QUERY_RESULT;
    '*[\n  _type == "post"\n  && slug.current != $slug\n  && (category == $category || count((tags)[@ in $tags]) > 0)\n]|order(publishedAt desc)[0...3]{\n  _id,\n  title,\n  excerpt,\n  content,\n  "slug": slug.current,\n  coverImage,\n  "author": {\n    "name": author->name,\n    "avatar": author->avatar\n  },\n  publishedAt,\n  readingTime,\n  category,\n  tags,\n  featured\n}': RELATED_POSTS_QUERY_RESULT;
    '*[\n  _type == "post"\n  && slug.current != $slug\n  && !(_id in $existingIds)\n]|order(publishedAt desc)[0...3]{\n  _id,\n  title,\n  excerpt,\n  content,\n  "slug": slug.current,\n  coverImage,\n  "author": {\n    "name": author->name,\n    "avatar": author->avatar\n  },\n  publishedAt,\n  readingTime,\n  category,\n  tags,\n  featured\n}': RECENT_POSTS_QUERY_RESULT;
    '*[\n  _type == "post"\n  && defined(slug.current)\n  && category == $category\n]|order(publishedAt desc){\n  _id,\n  title,\n  excerpt,\n  content,\n  "slug": slug.current,\n  coverImage,\n  "author": {\n    "name": author->name,\n    "avatar": author->avatar\n  },\n  publishedAt,\n  readingTime,\n  category,\n  tags,\n  featured\n}': POSTS_BY_CATEGORY_QUERY_RESULT;
    '*[\n  _type == "post"\n  && defined(slug.current)\n  && $tagName in tags\n]|order(publishedAt desc){\n  _id,\n  title,\n  excerpt,\n  content,\n  "slug": slug.current,\n  coverImage,\n  "author": {\n    "name": author->name,\n    "avatar": author->avatar\n  },\n  publishedAt,\n  readingTime,\n  category,\n  tags,\n  featured\n}': POSTS_BY_TAG_QUERY_RESULT;
    'array::unique(*[\n  _type == "post"\n  && defined(category)\n].category)': ALL_CATEGORIES_QUERY_RESULT;
    'array::unique(*[\n  _type == "post"\n  && defined(tags)\n].tags[])': ALL_TAGS_QUERY_RESULT;
    '*[\n  _type == "post"\n  && defined(slug.current)\n  && (\n    title match $searchPattern ||\n    excerpt match $searchPattern ||\n    content match $searchPattern ||\n    category match $searchPattern\n  )\n]|order(publishedAt desc){\n  _id,\n  title,\n  excerpt,\n  content,\n  "slug": slug.current,\n  coverImage,\n  "author": {\n    "name": author->name,\n    "avatar": author->avatar\n  },\n  publishedAt,\n  readingTime,\n  category,\n  tags,\n  featured\n}': SEARCH_POSTS_QUERY_RESULT;
    '*[\n  _type == "post"\n  && defined(slug.current)\n]{"slug": slug.current}': ALL_POST_SLUGS_QUERY_RESULT;
  }
}
